/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jcJkmmaQxSJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export function HomePage() {
  return (
    <section className='w-full py-20 md:py-32 lg:py-40'>
      <div className='container grid items-center justify-between gap-10 px-4 md:grid-cols-2 md:gap-20 lg:gap-32'>
        <div className='space-y-4 text-center md:text-left'>
          <h1 className='text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl'>
            Zoles Punkti
          </h1>
          <p className='max-w-[600px] text-slate-500 md:text-xl dark:text-slate-400'>
            Neskrien pēc lapas un pildspalvas, skaiti Zoles punktus šeit
          </p>
        </div>
        <div className='w-full max-w-md rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-950'>
          {/* <h2 className='mb-4 text-2xl font-bold'>Ielogojies un sāc skaitīt</h2> */}
          <form className='space-y-4'>
            <div className='space-y-2'>
              <Label htmlFor='email'>E-pasts</Label>
              <Input
                id='email'
                type='email'
                placeholder='m@example.com'
                required
              />
            </div>
            <div className='space-y-2'>
              <Label htmlFor='password'>Parole</Label>
              <Input id='password' type='password' required />
              <Link
                href='#'
                className='inline-block text-sm underline'
                prefetch={false}
              >
                Aizmirsi paroli?
              </Link>
            </div>
            <div className='flex gap-2'>
              <Button formAction={signup} type='submit' className='flex-1'>
                Ienākt
              </Button>
              <Link href='/register'>
                {' '}
                <Button variant='outline' className='flex-1'>
                  Reģistrēties
                </Button>
              </Link>
            </div>
          </form>
        </div>
      </div>
    </section>
  );
}
